// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMuwj5pzlf89cBEQQWsFBD35tRRXKurWs',
    appId: '1:488015560422:web:b71b0c76dc6b99d16ac527',
    messagingSenderId: '488015560422',
    projectId: 'flutterfirebase-63694',
    authDomain: 'flutterfirebase-63694.firebaseapp.com',
    storageBucket: 'flutterfirebase-63694.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWzbegiheAuz8CRP4SzAoYrIoMB5v_tF0',
    appId: '1:488015560422:android:48854fcbdc93ce0f6ac527',
    messagingSenderId: '488015560422',
    projectId: 'flutterfirebase-63694',
    storageBucket: 'flutterfirebase-63694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjHmZ5NTIzLoeEfXY7S1faKWxGw1Jhs4Y',
    appId: '1:488015560422:ios:521da62036f0b9db6ac527',
    messagingSenderId: '488015560422',
    projectId: 'flutterfirebase-63694',
    storageBucket: 'flutterfirebase-63694.appspot.com',
    iosClientId: '488015560422-aqbvda9raj7hhvvmao3k3brd5b2dgd8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.cubitAuthgoogle',
  );
}
